environment: prod

network:
  port: 3098
  containerTargetPort: 8000
  serviceEnabled: true

serviceAccount:
  name: secrets-csi-sa
  annotations: {
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxxxx:role/secrets-csi-role-production
  }

nodeSelector: {
  app_node_group: services
}

apps:
  - name: app
    resources:
      requests:
        cpu: "0.05"
        memory: "128M"
    replicaCount: 1
    command: [ "/bin/sh", "-c" ]
    args: [ "aerich", "upgrade", "&&", "python", "-m", "src.start_web" ]
    externalNlb: nlb-coursiv-service
    exposePort: true
    readinessProbe:
      httpGet:
        path: /health/
      initialDelaySeconds: 5
      periodSeconds: 5

  - name: worker
    resources:
      requests:
        cpu: "0.1"
        memory: "128M"
    replicaCount: 1
    command: [ "/bin/sh", "-c" ]
    args: [ "python", "-m", "src.start_worker" ]

  - name: scheduler
    resources:
      requests:
        cpu: "0.05"
        memory: "128M"
    replicaCount: 1
    command: [ "/bin/sh", "-c" ]
    args: [ "python", "-m", "src.start_scheduler" ]

secrets:
  awsSecretName: coursiv/production/ai-duty-agent
  envs:
    - name: DATABASE_URL
    - name: RABBITMQ_URL
    - name: SENTRY_DSN
    - name: ENVIRONMENT
    - name: OPENAI__API_KEY
    - name: OPENSEARCH__SERVICE_NAME
    - name: OPENSEARCH__KNOWLEDGE_BASE
    - name: OPENSEARCH__URL
    - name: AWS__REGION
    - name: AWS__ACCESS_KEY_ID
    - name: AWS__SECRET_ACCESS_KEY
    - name: AWS__S3_TIMEOUT
    - name: SLACK__TOKEN
    - name: SLACK__CHANNEL
    - name: GRAFANA__URL
    - name: GRAFANA__API_KEY
    - name: GRAFANA__ORG_ID
    - name: GRAFANA__CLOUDWATCH_DATASOURCE_UID
    - name: GRAFANA__LOKI_DATASOURCE_UID
    - name: GRAFANA__QUERY_URL
    - name: OPSGENIE__API_KEY
    - name: OPSGENIE__BASE_URL
    - name: OPSGENIE__USER
    - name: OPSGENIE__DEFAULT_TEAM
    - name: MEMORY_HOURS
    - name: MCP__RABBITMQ_URL
    - name: MCP__KUBERNETES_URL