environment: staging

network:
  port: 2017
  containerTargetPort: 8000
  serviceEnabled: true

serviceAccount:
  name: secrets-csi-sa
  annotations: {
    eks.amazonaws.com/role-arn: arn:aws:iam::hhhhhhh:role/secrets-csi-role-staging
  }

nodeSelector: {
  app_node_group: services
}

apps:
  - name: app
    resources:
      requests:
        memory: "192M"
        cpu: "0.1"
    replicaCount: 1
    command: [ "/bin/sh", "-c" ]
    args: [ "aerich", "upgrade", "&&", "python", "-m", "code.app" ]
    externalNlb: nlb-coursiv-service
    exposePort: true
    readinessProbe:
      httpGet:
        path: /health/
      initialDelaySeconds: 5
      periodSeconds: 5
  - name: consumer
    resources:
      requests:
        memory: "128M"
        cpu: "0.1"
    replicaCount: 1
    command: [ "/bin/sh", "-c" ]
    args: [ "aerich", "upgrade", "&&", "python", "-m", "code.consumers" ]
  - name: scheduler
    resources:
      requests:
        memory: "128M"
        cpu: "0.1"
    replicaCount: 1
    command: [ "/bin/sh", "-c" ]
    args: [ "aerich", "upgrade", "&&", "python", "-m", "code.scheduler" ]

secrets:
  awsSecretName: coursiv/staging/payments-solid
  envs:
    - name: DATABASE_URL
    - name: RABBITMQ_URL
    - name: SENTRY_DSN
    - name: REDIS_URL
    - name: ENVIRONMENT
    - name: SOLID_WEBHOOK_SECRET_KEY
    - name: SOLID_PUBLIC_KEY
    - name: SOLID_SECRET_KEY
    - name: USERS_URL
    - name: PAYMENTS_URL
    - name: OFFERS_URL
    - name: CHANNEL_DECRYPTION_KEY
    - name: GOOGLE_PAY_MERCHANT_ID
    - name: IS_GOOGLE_PAY_ENABLED
    - name: BIGQUERY_CREDENTIALS
    - name: BIGQUERY_DATASET_NAME
    - name: BIGQUERY_ORDER_VAT_TABLE_NAME
    - name: BIGQUERY_CANCELLED_SUBSCRIPTIONS_TABLE_NAME
    - name: BIGQUERY_ONECLICK_ORDERS_TABLE_NAME
    - name: PAYMENTS_MERCHANT_NAME
    - name: PAYPAL_SPLITTER_URL
    - name: ZIMRAN_ANALYTICS_BIGQUERY_CREDENTIALS
    - name: ZIMRAN_ANALYTICS_BIGQUERY_PROJECT_NAME
    - name: ZIMRAN_ANALYTICS_BIGQUERY_DATASET_NAME
    - name: ZIMRAN_ANALYTICS_BIGQUERY_TABLE_NAME
    - name: UPSELL_OFFERS_URL
