name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          .python-version: 3.11
      - run: |
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements-dev.txt
          ruff check src
          pytest tests
